# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_health_ind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHealthIndItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'community_health_ind_item',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'county',
            },
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_count', models.FloatField(blank=True, null=True)),
                ('avg_num_den', models.FloatField(blank=True, null=True)),
                ('measure', models.CharField(blank=True, max_length=10, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('mapping_distribution', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'health_data',
            },
        ),
        migrations.CreateModel(
            name='HealthTopic',
            fields=[
                ('htopic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'health_topic',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('indicator_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'indicator',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user',
            },
        ),
    ]
